
services:
  web:
    build:
      context: .
    env_file:
      - .env.local
    volumes:
      - ./:/var/www/html/
      - ~/.composer:/var/composer:cached
      - ./docker/web/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/web/dev/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/dev/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "80:80"

  selenium:
      image: selenium/standalone-chrome:112.0-chromedriver-112.0
      platform: linux/x86_64
      ports:
        - "4444:4444"
        - "7900:7900"
      shm_size: "2g"